### ISSUE TITLE
doctest 0.11 not supported

### ISSUE THREAD

**Issue by bergmark** [thoughtpolice/hs-ed25519#13]

**Comment by thoughtpolice** [comment]
Closed by 40db5d775ad340ff16897a11957a25a79647659d.

**Comment by peti** [comment]
It would be great to get a new release on Hackage that contains this fix. Or, you might also edit the existing release.

**Comment by thoughtpolice** [comment]
@peti Done - the existing `ed25519-0.0.5.0` on Hackage has been updated, so if you update the index you'll get a new version.

A new `ed25519-0.0.6.0` with rewritten docs (see #12) and some improved/deprecated APIs will be released probably within the week hopefully.
