### ISSUE TITLE
Windows: unknown symbol `__imp_CryptAcquireContextW'

### ISSUE THREAD

**Issue by domenkozar** [thoughtpolice/hs-ed25519#17]
http://sscce.org/ on Windows (Server 2012 R2 - Amazon AMI):

```
> dverify (PublicKey foo) "bar" (Signature "baz")
ghc.EXE: C:\sr\snapshots\a78c6a89\lib\x86_64-windows-ghc-8.0.1\ed25519-0.0.5.0-CpxZaSit3v24CALRG61NQp\HSed25519-0.0.5.0-CpxZaSit3v24CALRG61NQp.o: unknown symbol `__imp_CryptAcquireContextW'
```

cc @thoughtpolice

**Comment by domenkozar** [comment]
According to internetz this function so exist, so something fishy is going on with the linker? Only reference I could find is http://stackoverflow.com/questions/30608897/cryptacquirecontext-unresolved-external

**Comment by domenkozar** [comment]
Error is gone if I do `xcopy C:/Windows/System32/advapi32.dll .` and then `stack ghci`.

**Comment by thoughtpolice** [comment]
Sorry I missed this! That's a really bizarre one... I wonder if it's a linker bug? What GHC version are you using on that Windows server?

**Comment by domenkozar** [comment]
#18 solves this.
