### ISSUE TITLE
Please adjust version bound of ghc-prim for GHC 8.10 compat

### ISSUE THREAD

**Issue by vdukhovni** [thoughtpolice/hs-ed25519#28]
For GHC 8.10 the version bound of ghc-prim needs to be:
```
ghc-prim    >= 0.1 && < 0.7
```

**Comment by vdukhovni** [comment]
I see this is already covered in #27. Please merge #27 when you get a chance...

**Comment by thoughtpolice** [comment]
Done, and the cabal metadata on Hackage has been updated to adjust the bound accordingly, as well.
