### ISSUE TITLE
Needs update for QuickCheck 2.7

### ISSUE THREAD

**Issue by nomeata** [thoughtpolice/hs-ed25519#3]
Hi,

I’m getting build failures on Debian:

```
Preprocessing test suite 'properties' for ed25519-0.0.2.0...
[1 of 1] Compiling Main             ( tests/properties.hs, dist-ghc/build/properties/properties-tmp/Main.o )

tests/properties.hs:90:9:
    Constructor `Failure' should have 10 arguments, but has been given 8
    In the pattern: Failure n _ _ _ _ _ _ _
    In a case alternative: Failure n _ _ _ _ _ _ _ -> return (False, n)
    In a stmt of a 'do' block:
      case r of {
        Success n _ _ -> return (True, n)
        GaveUp n _ _ -> return (True, n)
        Failure n _ _ _ _ _ _ _ -> return (False, n)
        _ -> return (False, 0) }
make: *** [build-ghc-stamp] Error 1
```

http://aws-logs.debian.net/ftbfs-logs/2014/08/30/haskell-ed25519_0.0.2.0-2_unstable.log

It seems that you need to upgrade to the latest QuickCheck.

**Comment by peti** [comment]
We also get buildd failures in NixOS: http://hydra.cryp.to/build/1098563/nixlog/4/raw. Is this package still actively maintained? I see a fix has been provided in https://github.com/thoughtpolice/hs-ed25519/pull/4 long ago, but it's never been merged?
